baseURL = 'https://belfryupkeep.cccbr.org.uk'
languageCode = 'en-us'
title = 'Running a Tower'
theme = 'hugo-book'
sidebar_search_disable = true
publishDir = "docs/"

[params]
  BookLogo = 'favicon.png'
