baseURL = 'https://cccbr.github.io/belfryupkeep'
languageCode = 'en-us'
title = 'Belfry Upkeep'
theme = 'hugo-book'
sidebar_search_disable = true
publishDir = "public/"

[params]
  BookLogo = 'favicon.png'
