baseURL = 'https://cccbr.github.io/runningatower'
languageCode = 'en-uk'
title = 'Running a Tower'
theme = 'hugo-book'
sidebar_search_disable = true
publishDir = "docs/"

[params]
  BookLogo = 'favicon.png'
